# Generated by Django 3.1.7 on 2021-04-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210408_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='thumb_x_offset',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='art',
            name='thumb_y_offset',
            field=models.IntegerField(default=0),
        ),
    ]
