# Generated by Django 3.1.7 on 2021-04-15 09:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations
from django.db import models

import core.models


class Migration(migrations.Migration):

    replaces = [
        ("core", "0004_auto_20210414_1144"),
        ("core", "0005_auto_20210414_1459"),
    ]

    dependencies = [
        ("core", "0003_auto_20210408_1435"),
    ]

    operations = [
        migrations.AddField(
            model_name="art",
            name="description",
            field=models.TextField(
                blank=True, null=True, validators=[core.models.validate_text]
            ),
        ),
        migrations.AlterField(
            model_name="art",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(validators=[core.models.validate_text])),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "art",
                    models.ForeignKey(
                        default=1286,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.art",
                    ),
                ),
            ],
        ),
    ]
