# Generated by Django 3.1.7 on 2021-04-19 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_auto_20210414_1144_squashed_0005_auto_20210414_1459"),
    ]

    operations = [
        migrations.AddField(
            model_name="art",
            name="likes",
            field=models.ManyToManyField(
                related_name="likes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="art",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.art"
            ),
        ),
    ]
