# Generated by Django 3.1.7 on 2021-04-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210419_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='nsfw',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
