# Generated by Django 3.1.7 on 2021-04-23 10:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    replaces = [('core', '0007_art_thumb_render'), ('core', '0008_art_uuid')]

    dependencies = [
        ('core', '0006_art_nsfw'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='thumb_render',
            field=models.ImageField(default=b'', editable=False, upload_to='thumbs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='art',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
