# Generated by Django 3.1.7 on 2021-04-22 13:41

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_art_nsfw"),
    ]

    operations = [
        migrations.AddField(
            model_name="art",
            name="thumb_render",
            field=models.ImageField(default=b"", editable=False, upload_to="thumbs"),
            preserve_default=False,
        ),
    ]
