# Generated by Django 3.1.7 on 2021-04-26 08:28

import uuid

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_art_thumb_render_squashed_0008_art_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="art",
            name="thumb_render",
            field=models.ImageField(
                default="/home/honno/gdrive/GitHub/ascii-world/core/static/core/thumb.png",
                upload_to="thumbs",
            ),
        ),
        migrations.AlterField(
            model_name="art",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
