# Generated by Django 3.1.7 on 2021-04-26 08:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    replaces = [('core', '0008_auto_20210426_0828'), ('core', '0009_auto_20210426_0831'), ('core', '0010_auto_20210426_0849')]

    dependencies = [
        ('core', '0007_art_thumb_render_squashed_0008_art_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='thumb_render',
            field=models.ImageField(default='/home/honno/gdrive/GitHub/ascii-world/core/static/core/thumb.png', upload_to='thumbs'),
        ),
        migrations.AlterField(
            model_name='art',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='art',
            name='thumb_render',
            field=models.ImageField(default=None, upload_to='thumbs'),
        ),
        migrations.AlterField(
            model_name='art',
            name='thumb_render',
            field=models.ImageField(default='thumbs/default.png', upload_to='thumbs'),
        ),
    ]
