# Generated by Django 3.1.7 on 2021-04-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210426_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='thumb_render',
            field=models.ImageField(default='thumbs/default.png', upload_to='thumbs'),
        ),
    ]
