# Generated by Django 3.2 on 2021-05-18 09:19

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_art_native_thumb"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="nsfw_pref",
            field=models.CharField(
                choices=[("AA", "Always Ask"), ("SA", "Show All"), ("HA", "Hide All")],
                default="AA",
                max_length=2,
            ),
        ),
    ]
