# Generated by Django 3.2.3 on 2021-05-26 14:30

import django.core.validators
from django.db import migrations
from django.db import models

import core.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_user_nsfw_pref"),
    ]

    operations = [
        migrations.AlterField(
            model_name="art",
            name="description",
            field=models.TextField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        1, message="No text was submitted."
                    ),
                    core.models.validate_whitespace,
                    core.models.validate_emojis,
                    core.models.validate_tabs,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="art",
            name="native_thumb",
            field=models.TextField(
                validators=[
                    django.core.validators.MinLengthValidator(
                        1, message="No text was submitted."
                    ),
                    core.models.validate_whitespace,
                    core.models.validate_emojis,
                    core.models.validate_tabs,
                ]
            ),
        ),
        migrations.AlterField(
            model_name="art",
            name="text",
            field=models.TextField(
                validators=[
                    django.core.validators.MinLengthValidator(
                        1, message="No text was submitted."
                    ),
                    core.models.validate_whitespace,
                    core.models.validate_emojis,
                    core.models.validate_tabs,
                ]
            ),
        ),
        migrations.AlterField(
            model_name="art",
            name="title",
            field=models.CharField(
                max_length=80,
                validators=[
                    django.core.validators.MinLengthValidator(
                        1, message="No text was submitted."
                    ),
                    core.models.validate_whitespace,
                    core.models.validate_emojis,
                    core.models.validate_tabs,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(
                validators=[
                    django.core.validators.MinLengthValidator(
                        1, message="No text was submitted."
                    ),
                    core.models.validate_whitespace,
                    core.models.validate_emojis,
                    core.models.validate_tabs,
                ]
            ),
        ),
    ]
