# Generated by Django 3.2.3 on 2021-05-27 15:40

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_auto_20210526_1430"),
    ]

    operations = [
        migrations.AddField(
            model_name="art",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="updated_at",
            field=models.DateTimeField(default=None),
        ),
    ]
