# Generated by Django 3.2.3 on 2021-05-31 13:46

import django.utils.timezone
from django.db import migrations
from django.db import models

import core.models


class Migration(migrations.Migration):

    replaces = [
        ("core", "0014_auto_20210527_1540"),
        ("core", "0015_alter_comment_updated_at"),
        ("core", "0016_alter_art_updated_at"),
        ("core", "0017_auto_20210531_1238"),
    ]

    dependencies = [
        ("core", "0013_auto_20210526_1430"),
    ]

    operations = [
        migrations.AddField(
            model_name="art",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="updated_at",
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name="comment",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="art",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", core.models.CIUserManager()),
                ("_objects", core.models.CIUserManager(show_deleted=True)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
