# Generated by Django 3.2.3 on 2021-05-27 15:42

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_auto_20210527_1540"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
