# Generated by Django 3.2.3 on 2021-06-07 09:18

import django.core.validators
from django.db import migrations
from django.db import models

import core.models


class Migration(migrations.Migration):

    replaces = [("core", "0015_auto_20210601_1625"), ("core", "0016_alter_user_avatar")]

    dependencies = [
        ("core", "0014_auto_20210527_1540_squashed_0017_auto_20210531_1238"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.TextField(
                default="\n\n\n           ______\n         .´      `.\n   /.   /          \\\n   `.`.:            :\n   _.:'|   ,--------|\n   `-·´|  | v     v :\n       :  \\_.---`-._|\n    __  \\           ;\n ·-´\\_\\  :         /\n     \\_\\ :  ` . _.´\n      \\_(        :\n __.---´          `--._\n´                      '",
                validators=[
                    django.core.validators.MinLengthValidator(
                        1, message="No text was submitted."
                    ),
                    core.models.validate_whitespace,
                    core.models.validate_emojis,
                    core.models.validate_tabs,
                    core.models.validate_avatar_cols,
                    core.models.validate_avatar_rows,
                ],
            ),
        ),
    ]
