# Generated by Django 3.2.3 on 2021-06-01 16:25

import django.core.validators
from django.db import migrations
from django.db import models

import core.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_auto_20210527_1540_squashed_0017_auto_20210531_1238"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.TextField(
                default="\n\n       .adAMMMAbn.\n      dMMMMMMMMMMA.\n     'HMMMMMMMMMMMl.\n    db\\MMM^\"     \"^j\n    MMY   .        :\n    ,M|`,----. ,---.\n    :,' \\    ;^:   ;\n     q|  `--'  )`--\n     ,:            ;\n    /: \\    `---  :\n   /    \"-.__  _.'\n  (    \\       ;\n.' '.   `      :-.\n     '.   `   '/  \"-.\n       \"-.__\"_/      \"-.\n",
                validators=[
                    django.core.validators.MinLengthValidator(
                        1, message="No text was submitted."
                    ),
                    core.models.validate_whitespace,
                    core.models.validate_emojis,
                    core.models.validate_tabs,
                    core.models.validate_avatar_cols,
                    core.models.validate_avatar_rows,
                ],
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
