# Generated by Django 3.2.3 on 2021-05-31 10:15

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_comment_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="art",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
