# Generated by Django 3.2.3 on 2021-06-07 10:26

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_auto_20210601_1625_squashed_0016_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="description",
            field=models.TextField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(100)],
            ),
        ),
    ]
