# Generated by Django 3.2.3 on 2021-06-08 08:45

import django.core.validators
from django.db import migrations
from django.db import models

import core.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.TextField(
                default="\n\n\n           ______\n         ,'      `.\n   /.   /          \\\n   `.`.:            :\n   _.:'|   ,--------|\n   `-·´|  | v     v :\n       :  \\_.---`-._|\n    __  \\           ;\n ·-´\\_\\  :         /\n     \\_\\ :  ` . _.´\n      \\ (        :\n __.---´          `--._\n´                      '",
                validators=[
                    django.core.validators.MinLengthValidator(
                        1, message="No text was submitted."
                    ),
                    core.models.validate_whitespace,
                    core.models.validate_emojis,
                    core.models.validate_tabs,
                    core.models.validate_avatar_cols,
                    core.models.validate_avatar_rows,
                ],
            ),
        ),
    ]
