# Generated by Django 3.2.3 on 2021-06-10 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_alter_user_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="art",
            name="native_thumb",
        ),
    ]
