# Generated by Django 3.2.3 on 2021-06-10 14:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations
from django.db import models

import core.models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0019_remove_art_native_thumb"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="art",
            name="text",
        ),
        migrations.AddField(
            model_name="art",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_core.art_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.CreateModel(
            name="PlaintextArt",
            fields=[
                (
                    "art_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.art",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        validators=[
                            django.core.validators.MinLengthValidator(
                                1, message="No text was submitted."
                            ),
                            core.models.validate_whitespace,
                            core.models.validate_emojis,
                            core.models.validate_tabs,
                        ]
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.art",),
        ),
    ]
