# Generated by Django 3.2.3 on 2021-06-19 10:03

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_remove_art_native_thumb"),
    ]

    operations = [
        migrations.AddField(
            model_name="art",
            name="markup",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="art",
            name="native_thumb",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
