# Generated by Django 3.1.7 on 2021-03-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='title',
            field=models.CharField(default='art', max_length=80),
        ),
    ]
